# Generated by Django 6.0.3 on 2026-04-06 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('subjects', models.CharField(choices=[('Ma', 'Math'), ('Sci', 'Science'), ('Mar', 'Marathi'), ('Hin', 'Hindi'), ('Eng', 'English'), ('His', 'History'), ('Geo', 'Geography')], max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
            ],
        ),
    ]
