# Generated by Django 6.0.3 on 2026-04-06 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('profession', models.CharField(choices=[('Ai', 'Ai Engineer'), ('Data', 'Data Scientist'), ('Fron', 'FrontEnd Developer'), ('Back', 'BackEnd Developer'), ('Anyl', 'Data Analyst')], max_length=4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
