# Generated by Django 6.0.3 on 2026-03-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('f_name', models.CharField(verbose_name='100')),
                ('l_name', models.CharField(verbose_name='100')),
                ('course', models.CharField(verbose_name='100')),
                ('admission_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='100')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.student')),
            ],
        ),
    ]
