# Generated by Django 6.0.3 on 2026-04-07 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 7, 9, 26, 23, 824590, tzinfo=datetime.timezone.utc)),
        ),
    ]
